_id: spc_191b0c04b8cd43f5b10d755f938c0444
type: ApiSpec
parentId: wrk_58044925e8cc4c99a8275a1ae1450908
modified: 1733233642110
created: 1733131178404
fileName: CI/CD example flows from Insomnia to Konnect
contents: >
  openapi: 3.0.0

  servers:
    - url: https://httpbin.apim.eu
    - url: https://httpbin.konghq.com
  info:
    contact:
      email: me@kennethreitz.org
      url: https://kennethreitz.org
      name: Kenneth Reitz
    description: |
      This service and the GutHub repo this OpenOPI is living in is about showing all the different ways of automation using the Kong tool chain.
      
      1. OpenAPI designing in Insomnia
      2. Using collections to test auto APIs
      3. Creating test collection
      4. Automating the creation of a sandbox / mockup version in Kong Gateway
      5. Propagate automatically to the Kong Gateway
      6. Publish and document on the Konnect Developer Portal

      The original httpbin service is free - but **think about giving an ice cream to the developer**

      ![Developer wants an ice cream](https://images.pexels.com/photos/5060281/pexels-photo-5060281.jpeg?cs=srgb&dl=pexels-roman-odintsov-5060281.jpg&fm=jpg&w=200) 
    title: CI/CD example flows from Insomnia to Konnect
    version: 3.8.1.0
  paths:
    /uuid:
      get:
        description: Generate and get an UUID
        operationId: get_uuid
        responses:
          "200":
            description: A UUID4.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    uuid:
                      type: string
                      description: The UUID
                examples:
                  counting:
                    value:
                      uuid: 1234-5678-901234567-890
                  text:
                    value:
                      uuid: aaaa-bbbb-ccccccc-dddd
                  random:
                    value:
                      uuid: A99FE500-4AC4-4E63-87D0-EC508A10535F
        summary: Return a UUID4.
        tags:
          - Generate UUID
    /anything/query:
      get:
        description: returns all your query parameters
        operationId: query
        parameters:
          - in: query
            name: exampleParam
            required: true
            schema:
              type: integer
              minimum: 5
              maximum: 25
            examples:
              valid:
                value: 22
            description: A value between 5 and 25
        responses:
          "200":
            description: The anything endpoint but with limitation on query
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Anything"
                examples:
                  example1:
                    value:
                      args:
                        exampleParam: Parameter value
                      data: "Mocked Query data"
                      files: {}
                      form: {}
                      headers:
                        "Accept": "text/html,application/xhtml+xml,application/xml"
                        "Accept-Encoding": "gzip, deflate, br, zstd"
                        "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"
                        "Connection": "keep-alive" 
                        "Host": "httpbin.apim.eu" 
                      "json": "null"
                      "method": "GET"
                      "origin": "10.244.0.1"
        summary: Return anything data.
        tags:
          - Anything
          - Query
        x-kong-plugin-request-validator:
          enabled: true
    /anything/catOrDog:
      post:
        description: create a new pet
        operationId: create_pet
        requestBody:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Cat'
                  - $ref: '#/components/schemas/Dog'
        responses:
          "200":
            description: A post request only allowing a cat or dog object
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Anything"
                examples:
                  dog:
                    value:
                      args: {}
                      data: "{\"barks\": true,\"breed\": \"Husky\"}"
                      files: {}
                      form: {}
                      headers:
                        "Accept": "text/html,application/xhtml+xml,application/xml"
                        "Accept-Encoding": "gzip, deflate, br, zstd"
                        "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"
                        "Connection": "keep-alive" 
                        "Host": "httpbin.apim.eu" 
                      "json": "{\"breed\": \"Husky\",\"barks\": true}"
                      "method": "GET"
                      "origin": "10.244.0.1"
                  cat:
                    value:
                      args: {}
                      data: "{\n  \"hunts\": true,\n  \"age\": 0}"
                      files: {}
                      form: {}
                      headers:
                        "Accept": "text/html,application/xhtml+xml,application/xml"
                        "Accept-Encoding": "gzip, deflate, br, zstd"
                        "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"
                        "Connection": "keep-alive" 
                        "Host": "httpbin.apim.eu" 
                      "json": "{\"age\": 0,\"hunts\": true}"
                      "method": "GET"
                      "origin": "10.244.0.1"
        summary: To bark or not to bark
        tags:
          - Anything
          - CatOrDog
        x-kong-plugin-rate-limiting-advanced:
          enabled: true
          config:
            limit:
              - 3
            window_size:
              - 60
            namespace: hlferuifgevhrlgzff63
    /delay/{delay}: 
      get:
        description: delay a responses by a defined number of secondes
        operationId: delay
        parameters:
          - in: path
            name: delay
            required: true
            schema:
              type: integer
              minimum: 0
              maximum: 10
            description: The delay in seconds
        responses:
          "200":
            description: Returns a delayed response
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Anything"
                examples:
                  example1:
                    value:
                      args: {}
                      data: "Mocked Delayed Response data"
                      files: {}
                      form: {}
                      headers:
                        "Accept": "text/html,application/xhtml+xml,application/xml"
                        "Accept-Encoding": "gzip, deflate, br, zstd"
                        "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"
                        "Connection": "keep-alive" 
                        "Host": "httpbin.apim.eu" 
                      "json": "null"
                      "method": "GET"
                      "origin": "10.244.0.1"
        summary: Returns a delayed response (max of 10 seconds).
        tags:
          - Delayed Response
          - Path
    /status/{codes}:
      get:
        description: returns a http status code
        operationId: status_code
        parameters:
          - in: path
            name: codes
            required: true
            schema:
              type: integer
              minimum: 200
              maximum: 599
            description: The HTTP status code (200-599)
        responses:
          "200":
            description: Success
          "300":
            description: Redirection
          "400":
            description: Client errors
          "500":
            description: Server errors
        summary: Return status code or random status code if more than one are given
        tags:
          - Status Codes
          - Path
  components:
    securitySchemes:
      KeyCloak:
        type: openIdConnect
        openIdConnectUrl: https://keycloak.apim.eu/auth/realms/kong/.well-known/openid-configuration
        x-kong-security-openid-connect:
          config:
            client_id: 
              - blog_post
            client_secret: 
              - a5186adc-b5e2-4501-85a8-eb19a5e1a2a3
            ssl_verify: false
            consumer_claim:
              - email
            verify_signature: false
            redirect_uri:
               - http://localhost:8000/anything/query
            consumer_optional: true
    schemas:
      Dog:
        type: object
        properties:
          bark:
            type: boolean
          breed:
            type: string
            enum: [Dingo, Husky, Retriever, Shepherd]
      Cat:
        type: object
        properties:
          hunts:
            type: boolean
          age:
            type: integer
      Anything:
        type: object
        properties:
          args: 
            type: object
            items:
              type: object
          data:
            type: string
          files: 
            type: object
            items:
              type: object
          form: 
            type: object
            items:
              type: object
          headers: 
            type: object
            items:
              type: object    
          json:
            type: string
          method:
            type: string
          origin:
            type: string
          url:
            type: string
  tags:
    - description: Creates a random UUID and returns it in a JSON structure
      name: Generate UUID
    - name: Anything
    - name: Query
    - name: CatOrDog
    - name: Delayed Response
    - name: Path
    - name: Status Codes
contentType: yaml
